# NumPy 

 __NumPy (Numerical Python)__ is the fundamental package for scientific computing with Python. It is used for mathematical computaions of arrays and matrices,  along with the help of some mathematical functions to opearte on these arrays. 

In [1]:
# Importing package
import numpy as np

### NumPy Basics ###

To create a numpy 1D array and a 2D array.

In [2]:
# Creating a NumPy array from a python list
a = np.array([5,9,0,1,3,9,10])
a

array([ 5,  9,  0,  1,  3,  9, 10])

In [3]:
# Creating a NumPy array
b = np.array([1,0,5,9,1,2,11])
b

array([ 1,  0,  5,  9,  1,  2, 11])

In [4]:
# Accessing elemnts of the array
b[0]

1

In [5]:
# To check the dimension of b (Here it's a one-dimensional array)
b.ndim

1

In [6]:
# Shape function : returns shape of an array - for array it returns the length of the array.
a.shape

(7,)

In [7]:
# To check the data type of element in the numpy array
a.dtype

dtype('int32')

In [8]:
# Creating numpy 2D array : From a python list of lists
M = np.array([[3,7,8],[1,9,0],[3,99,7]])
M

array([[ 3,  7,  8],
       [ 1,  9,  0],
       [ 3, 99,  7]])

In [9]:
# Accessing elemnts of the array
# Using position as index 3rd row(2) and 2nd column(1) i.e, [2,1]
M[2,1]

99

In [10]:
M.dtype

dtype('int32')

In [11]:
M.shape

(3, 3)

In [12]:
countries = np.array(['India','Netherlands','Malaysia','Australia','New Zealand','Spain'])
countries

array(['India', 'Netherlands', 'Malaysia', 'Australia', 'New Zealand',
       'Spain'],
      dtype='<U11')

In [13]:
# Accessing a set of elements
countries[0:4]

array(['India', 'Netherlands', 'Malaysia', 'Australia'],
      dtype='<U11')

In [14]:
names = np.array([['Jeswin','George'],['Ravi','Ranjan'],['Toshiba','Chamoli']])
print(names)

[['Jeswin' 'George']
 ['Ravi' 'Ranjan']
 ['Toshiba' 'Chamoli']]


In [15]:
names[0,0]

'Jeswin'