# NumPy functions : - arange() and linspace()

In [1]:
# Importing package
import numpy as np

## 1. numpy.arange([start, ]stop, [step, ])
_The terms in square brackets start and step are optional._

This function returns a numpy array with evenly spaced values within a given interval. The numpy array starts with the _start element_  but will exclude the _stop element_. 

In [4]:
# By default the array will start from 0 and end at a value less than 5 ; with even spaces(or, step size) of 1.
np.arange(5)

array([0, 1, 2, 3, 4])

In [13]:
type(np.arange(5))

numpy.ndarray

In [5]:
np.arange(3,9)

array([3, 4, 5, 6, 7, 8])

In [7]:
np.arange(3,13,1)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
np.arange(3,13,2)

array([ 3,  5,  7,  9, 11])

In [14]:
np.arange(4.5)

array([ 0.,  1.,  2.,  3.,  4.])

In [17]:
np.arange(1.4,4.4,0.1)

array([ 1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,  2.3,  2.4,
        2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,  3.4,  3.5,
        3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4])

From above example, results of numpy.arange() are not consistent with non-integer numbers. So for these cases _numpy.linspace_ is preferred.

## 2. numpy.linspace(start, stop, [num],endpoint=True, retstep=False)

Returns a numpy array having __num__ evenly spaced samples, calculated over the interval __[start, stop]__.

__num :__ (Optional) Number of samples to generate. Default is 50. Must be non-negative.

If (Optional) __endpoint = True :__ stop is the last sample i.e., it will be included in the resulting series.

   __endpoint = False :__ stop won't be the last sample i.e., it will be excluded from the resulting series.
   
   By default, endpoint is set as True.
   
__retstep__: (Optional) If True, return (samples, step), where step is the spacing between samples. By default, it's False.
   
   


In [19]:
# This command will result in a numpy array having 50 samples between 5 and 8. 
np.linspace(5,8)

array([ 5.        ,  5.06122449,  5.12244898,  5.18367347,  5.24489796,
        5.30612245,  5.36734694,  5.42857143,  5.48979592,  5.55102041,
        5.6122449 ,  5.67346939,  5.73469388,  5.79591837,  5.85714286,
        5.91836735,  5.97959184,  6.04081633,  6.10204082,  6.16326531,
        6.2244898 ,  6.28571429,  6.34693878,  6.40816327,  6.46938776,
        6.53061224,  6.59183673,  6.65306122,  6.71428571,  6.7755102 ,
        6.83673469,  6.89795918,  6.95918367,  7.02040816,  7.08163265,
        7.14285714,  7.20408163,  7.26530612,  7.32653061,  7.3877551 ,
        7.44897959,  7.51020408,  7.57142857,  7.63265306,  7.69387755,
        7.75510204,  7.81632653,  7.87755102,  7.93877551,  8.        ])

In [20]:
np.linspace(2.0, 6.0, num=5, endpoint=False)

array([ 2. ,  2.8,  3.6,  4.4,  5.2])

In [21]:
np.linspace(2.0, 6.0, num=5, endpoint=True)

array([ 2.,  3.,  4.,  5.,  6.])

In [23]:
np.linspace(2.0, 6.0, num=5, endpoint=False,retstep=True)

(array([ 2. ,  2.8,  3.6,  4.4,  5.2]), 0.80000000000000004)

Here the step size choosen by numpy is 0.8