# NumPy : Indexing, in palce & not in place and slicing of arrays 

In [1]:
# Importing package
import numpy as np

## Indexing

In [2]:
a = np.array([1,2,3,4,8,5,6])  # Create a numpy array
a

array([1, 2, 3, 4, 8, 5, 6])

In [3]:
b = [False,True,False,True,False,True,False] # Create a python list having boolean values
b

[False, True, False, True, False, True, False]

In [4]:
type(b)

list

In [5]:
a[b] # Obtaining a numpy array from a and b where list b helps in indexing using the True value
      # # This results in a numpy array

array([2, 4, 5])

In [6]:
# Checking the above result with a numpy boolean array
b = np.array(b) 
type(b)

numpy.ndarray

In [7]:
a[b]  # This results in a numpy array

array([2, 4, 5])

In [8]:
a[a>3] # This results in a numpy array as [a>3] creates a boolean array and based on its True values, values of a is assigned. 

array([4, 8, 5, 6])

In [9]:
a    # Observe that the vaslue of a has not changed

array([1, 2, 3, 4, 8, 5, 6])

In [10]:
c = a>2   # Creating a numpy boolean array with help of a numpy array and conditinal statements for indexing 
c

array([False, False,  True,  True,  True,  True,  True], dtype=bool)