In [1]:
import numpy as np

## Q1. To find maximum or minimum along a row or a column of a matrix

In [2]:
a = np.array( [ [10,2], [3,4], [5,6] ] )
a

array([[10,  2],
       [ 3,  4],
       [ 5,  6]])

In [3]:
# Maximum along the columns
xmax , ymax = a.max(axis = 0)
print xmax,ymax

10 6


In [4]:
# Maximum along the rows
xmax , ymax = a.max(axis = 1)
print xmax,ymax

ValueError: too many values to unpack

This error is caused when there are more values in whatever is being unpacked than the amount of variables you have specified to be read into. The solution is to specify a matching number of variables to be read into as are being unpacked.  
So redoing it with more variables.

In [5]:
# Maximum along the rows
xmax , ymax, zmax = a.max(axis = 1)
print xmax,ymax, zmax

10 4 6


## Q2. How to sort 2D array (numpy.ndarray) based to the second column in python?

Use ```.argsort()``` it returns an ```numpy.array``` of indices that sort the given numpy.array. You call it as a function or as a method on your array.

In [6]:
arr = np.array([[-0.30565392, -0.96605562],
                [ 0.85331367, -2.62963495],
                [ 0.87839643, -0.28283675],
                [ 0.72676698,  0.93213482],
                [-0.52007354,  0.27752806],
                [-0.08701666,  0.22764316],
                [-1.78897817,  0.50737573],
                [ 0.62260038, -1.96012161],
                [-1.98231706,  0.36523876],
                [-1.07587382, -2.3022289 ]])

You can now call ```.argsort()``` on the column you want to sort, and it will give you an array of row indices that sort that particular column which you can pass as an index to your original array.

In [7]:
arr[ arr[:,1].argsort() ]   # Happens in-place
arr

array([[-0.30565392, -0.96605562],
       [ 0.85331367, -2.62963495],
       [ 0.87839643, -0.28283675],
       [ 0.72676698,  0.93213482],
       [-0.52007354,  0.27752806],
       [-0.08701666,  0.22764316],
       [-1.78897817,  0.50737573],
       [ 0.62260038, -1.96012161],
       [-1.98231706,  0.36523876],
       [-1.07587382, -2.3022289 ]])

You can equivalently use ```numpy.argsort()```

In [8]:
A = np.array([[1,2,3],[4,5,6],[0,0,1]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 1]])

In [9]:
A[ np.argsort(A[: , 2]) ]   # 2 represents the 3rd column

array([[0, 0, 1],
       [1, 2, 3],
       [4, 5, 6]])