# Operations on NumPy arrays

## Numpy arrays support Vectorized operations 
So it will always be element-wise operations.

In [1]:
# Importing package
import numpy as np

In [2]:
# Creating two NumPy arrays
a = np.array([4,2,1,3,7])
b = np.array([1,2,3,4,5])
print('a : ', a)
print('b : ', b)

a :  [4 2 1 3 7]
b :  [1 2 3 4 5]


In [3]:
# Creating a 2-dimensional array
c = np.array([[1,2,6],[2,5,10]])
d = np.array([[1,2,1],[2,3,7]])
c

array([[ 1,  2,  6],
       [ 2,  5, 10]])

In [4]:
d

array([[1, 2, 1],
       [2, 3, 7]])

### Basic mathematical operation +,-,*,/

In [5]:
a + b

array([ 5,  4,  4,  7, 12])

In [6]:
a/b

array([ 4.        ,  1.        ,  0.33333333,  0.75      ,  1.4       ])

In [7]:
a-b

array([ 3,  0, -2, -1,  2])

In [8]:
c + d

array([[ 2,  4,  7],
       [ 4,  8, 17]])

### Mathematical operations of a NumPy array and  a scalar

In [9]:
a * 3

array([12,  6,  3,  9, 21])

In [10]:
b/2

array([ 0.5,  1. ,  1.5,  2. ,  2.5])

In [11]:
b + 5

array([ 6,  7,  8,  9, 10])

In [12]:
c * 2

array([[ 2,  4, 12],
       [ 4, 10, 20]])

## Logical operations on NumPy arrays

__In Numpy__, if m and n are two boolean numpy arrays. 

m & n performs a __bitwise and__ opeartion an m and n. 

m | n performs a __bitwise or__ operation on m and n.

~m performs a __bitwise not__ opeartion on m.

In [13]:
# Create two numpy boolean arrays
m = np.array([True, False, False, True, True])
n = np.array([False, False, True, False, True])
print('m : ', m)
print('n : ', n)
m.dtype

m :  [ True False False  True  True]
n :  [False False  True False  True]


dtype('bool')

In [14]:
~m

array([False,  True,  True, False, False], dtype=bool)

In [15]:
# Bitwise And
m & n

array([False, False, False, False,  True], dtype=bool)

In [16]:
x = np.array([True,False])
y = np.array([True,True])
x|y

array([ True,  True], dtype=bool)

If array contains boolean data type then performing logical and/or/not is same as performing bitwise and/or/not respectively.

In [17]:
np.logical_or([True,False],[False,True])

array([ True,  True], dtype=bool)

In [18]:
z = np.arange(5)
z

array([0, 1, 2, 3, 4])

In [19]:
np.logical_not(z>2)

array([ True,  True,  True, False, False], dtype=bool)

In [20]:
np.logical_and(z<3,z>2)

array([False, False, False, False, False], dtype=bool)

In [21]:
np.logical_not([0,1,5,True,False,19])

array([ True, False, False, False,  True, False], dtype=bool)