# NumPy : Indexing and slicing of arrays 

In [1]:
# Importing package
import numpy as np

## Indexing

In [3]:
a = np.array([1,2,3,4,8,5,6])  # Create a numpy array
a

array([1, 2, 3, 4, 8, 5, 6])

In [4]:
b = [False,True,False,True,False,True,False] # Create a python list having boolean values
b

[False, True, False, True, False, True, False]

In [6]:
type(b)

list

In [17]:
a[b] # Obtaining a numpy array from a and b where list b helps in indexing using the True value
      # # This results in a numpy array

array([3, 4, 8, 5, 6])

In [7]:
# Checking the above result with a numpy boolean array
b = np.array(b) 
type(b)

numpy.ndarray

In [10]:
a[b]  # This results in a numpy array

array([2, 4, 5])

In [11]:
a[a>3] # This results in a numpy array

array([4, 8, 5, 6])

In [12]:
a    # Observe that the vaslue of a has not changed

array([1, 2, 3, 4, 8, 5, 6])

In [16]:
c = a>2   # Creating a numpy boolean array with help of a numpy array and conditinal statements for indexing 
c

array([False, False,  True,  True,  True,  True,  True], dtype=bool)

## Inplace vs not-in-place

using operators += and  +

* += ---> Operates in place

* + ---> Doesn't operate in place

In [19]:
# Case 1 : Using +=
m = np.array([1,2,3,4])
n = m  # So here both a and b point to same array

In [20]:
m

array([1, 2, 3, 4])

In [21]:
n

array([1, 2, 3, 4])

In [23]:
m += np.array([1,1,1,1]) # This operation will modify the existing array
m

array([3, 4, 5, 6])

In [25]:
n        # n also changes according to m

array([3, 4, 5, 6])

In [ ]:
# Case 2: 