# [NumPy Tutorial](http://scipy.github.io/old-wiki/pages/Tentative_NumPy_Tutorial)

## Basics
NumPy's main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.   
- In Numpy dimensions are called __axes__. 
- The number of axes is __rank__.
- Eg : [1, 2, 1] is an array of rank 1, because it has one axis. That axis has a length of 3.
- Eg : [[ 1., 0., 0.],  
     [ 0., 1., 2.]]    
      the array has rank 2 (it is 2-dimensional). The first dimension (axis) has a length of 2, the second dimension has a length of 3.  
      
Numpy's array class is called __ndarray__.  

### 1. ndarray.ndim
the number of axes (dimensions) of the array. In the Python world, the number of dimensions is referred to as __rank__.

In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.ndim

2

### 2. ndarray.shape
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be ```(n,m```. The length of the shape tuple is therefore the __rank__, or number of dimensions, __ndim__.

In [4]:
a.shape

(3, 5)

### 3. ndarray.size
the total number of elements of the array. This is equal to the product of the elements of shape.

In [5]:
a.size

15

### 4. ndarray.dtype
an object describing the type of the elements in the array. One can create or specify dtype's using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

In [6]:
a.dtype

dtype('int32')

In [7]:
a.dtype.name

'int32'

### 5. ndarray.itemsize
the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has __itemsize 4__ (=32/8). It is equivalent to __ndarray.dtype.itemsize__.

In [8]:
a.itemsize

4

In [9]:
a.dtype.itemsize

4

### 6. ndarray.data
the buffer containing the actual elements of the array. Normally, we won't need to use this attribute because we will access the elements in an array using indexing facilities.

In [10]:
a.data

In [11]:
type(a)

numpy.ndarray

## Array Creation

In [12]:
b = np.array( [ (1.5,2,3), (4,5,6) ] )
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

The type of the array can also be explicitly specified at creation time:

In [13]:
c = np.array( [ [1,2], [3,4] ], dtype = complex )
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.

The function __zeros__ creates an array full of zeros, the function __ones__ creates an array full of ones, and the function __empty__ creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.

In [14]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [15]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [16]:
np.empty((3,3))

array([[  0.00000000e+000,   2.68771711e-321,   2.47032823e-323],
       [  5.14172501e-312,   0.00000000e+000,   2.47032823e-323],
       [  5.14172506e-312,   0.00000000e+000,   1.33509117e-306]])

## np.arange()

To create sequences of numbers, NumPy provides a function analogous to range that returns a numpy array.

In [17]:
a = np.arange(10,30,5)
a

array([10, 15, 20, 25])

In [18]:
type(a)

numpy.ndarray

## np.linspace()
When __arange__ is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function __linspace__ that receives as an argument the number of elements that we want, instead of the step:

In [19]:
b = np.linspace(0,2,9)  # Return 9 numbers from 0 to 9
b

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [20]:
type(b)

numpy.ndarray

## Random

In [21]:
from numpy.random import *

In [22]:
rand(3,2)    # Number btwn 0 and 1

array([[ 0.99964628,  0.40389866],
       [ 0.90300976,  0.84258929],
       [ 0.8076203 ,  0.00138399]])

In [23]:
randn(3,2)   # random normal distribution

array([[ 0.07148113,  1.60088676],
       [ 0.35884046,  0.73966614],
       [ 0.95232958, -2.20677918]])

In [24]:
randint(4,14,(3,3))

array([[ 6,  8,  5],
       [ 9,  9,  5],
       [13, 13,  5]])

## Basic Operations
Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [25]:
a = np.arange(10,90,5)
a

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85])

In [26]:
10 * np.sin(a)

array([-5.44021111,  6.5028784 ,  9.12945251, -1.3235175 , -9.88031624,
       -4.28182669,  7.4511316 ,  8.50903525, -2.62374854, -9.99755173,
       -3.04810621,  8.26828679,  7.73890682, -3.87781635, -9.93888654,
       -1.7607562 ])

In [27]:
a < 50

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False, False], dtype=bool)

####  the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the dot function 

In [28]:
A = np.array( [ [2,5,1],[8,0,1],[1,2,1] ] )
A

array([[2, 5, 1],
       [8, 0, 1],
       [1, 2, 1]])

In [29]:
B = np.array( [ [1,3,2],[1,8,10],[1,2,1] ] )
B

array([[ 1,  3,  2],
       [ 1,  8, 10],
       [ 1,  2,  1]])

In [30]:
A * B  # elementwise product

array([[ 2, 15,  2],
       [ 8,  0, 10],
       [ 1,  4,  1]])

In [31]:
np.dot(A,B)  # matrix product

array([[ 8, 48, 55],
       [ 9, 26, 17],
       [ 4, 21, 23]])

#### Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

In [32]:
from numpy.random import *

In [33]:
a = np.ones((3,2), dtype = int)    # The matrix size must be inside brackets
a                           # if dtype not specified as int by default it will take float

array([[1, 1],
       [1, 1],
       [1, 1]])

In [34]:
b = randint(1,10,(3,2))
b

array([[6, 6],
       [8, 1],
       [2, 8]])

In [35]:
b += a
b

array([[7, 7],
       [9, 2],
       [3, 9]])

#### Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

In [36]:
b.max()

9

In [37]:
a.min()

1

In [38]:
a.sum()

6

#### By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter you can apply an operation along the specified axis of an array:

In [39]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
b.sum(axis = 0)

array([12, 15, 18, 21])

In [41]:
b.min(axis=1)

array([0, 4, 8])

In [42]:
b.cumsum(axis = 0 )

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]], dtype=int32)

## Universal Functions

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called "universal functions"(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [43]:
B = np.arange(4)
B

array([0, 1, 2, 3])

In [44]:
np.exp(B)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692])

In [45]:
np.sqrt(B)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081])

## Copies and Views

When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not. This is often a source of confusion for beginners. There are three cases:  

### Case 1 : No copy at all

Simple assignments make no copy of array objects or of their data.

In [46]:
a = np.arange(12)
b = a

In [47]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Python passes mutable objects as references, so function calls make no copy

In [49]:
id(a)

1040762180032

In [50]:
id(b)

1040762180032

In [51]:
def f(x):
    print(id(x))

In [52]:
f(a)

1040762180032


In [53]:
b is a    # a and b are two names for the same ndarray object

True

In [54]:
b[1] = 99
b

array([ 0, 99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [55]:
a

array([ 0, 99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Case 2 :  View or Shallow Copy

Different array objects can share the same data. The __view__ method creates a new array object that looks at the same data.

In [56]:
a

array([ 0, 99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [57]:
c = a.view()    # c is a view of the data owned by a
c

array([ 0, 99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [58]:
c is a      # Not object for same array

False

In [59]:
c.base is a                        # c is a view of the data owned by a

True

In [60]:
c.shape = 2,6

In [61]:
c

array([[ 0, 99,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [62]:
a

array([ 0, 99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [63]:
a.shape

(12,)

In [64]:
c[0,4] = 1234
a

array([   0,   99,    2,    3, 1234,    5,    6,    7,    8,    9,   10,
         11])

In [65]:
a.shape = 2,6
a

array([[   0,   99,    2,    3, 1234,    5],
       [   6,    7,    8,    9,   10,   11]])

#### Slicing an array returns a view of it:

In [66]:
s = a[:, 1:3]
s

array([[99,  2],
       [ 7,  8]])

In [67]:
s[:] = 10
s

array([[10, 10],
       [10, 10]])

In [68]:
a

array([[   0,   10,   10,    3, 1234,    5],
       [   6,   10,   10,    9,   10,   11]])

In [69]:
k = a[:, 3:]
k

array([[   3, 1234,    5],
       [   9,   10,   11]])

In [71]:
k = 10    #Note the difference between s=10 and s[:]=10
k

10

## Case 3 : Deep Copy

The __copy__ method makes a complete copy of the array and its data.

In [72]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [73]:
d = a.copy()
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [74]:
d is a      # d is not a view of a

False

In [75]:
d.base is a                           # d doesn't share anything with a

False

In [76]:
d[0,0] = 99
d

array([[99,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [77]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### np.delete()

Return a new array with sub-arrays along an axis deleted. For a one dimensional array, this returns those entries not returned by arr[obj]

In [78]:
arr = np.array( [ [1,2,3,4], [5,6,7,8],[9,10,11,12] ] )
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [79]:
arr_c = arr.copy()
arr_c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [80]:
np.delete(arr,1,axis = 0)   # Having a bit confusion using axis

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [81]:
np.delete(arr_c,1, axis = 1)

array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12]])

In [82]:
mn = np.array([3,8,6,4,1,0,11,66,54])
mn

array([ 3,  8,  6,  4,  1,  0, 11, 66, 54])

In [83]:
np.delete(mn,7)   # Deleting element 66 having index 7

array([ 3,  8,  6,  4,  1,  0, 11, 54])

Refer [numpy.insert](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.insert.html#numpy.insert) 
and [numpy.append](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.append.html#numpy.append)

## np.insert(arr, obj, values, axis=None)

Insert values along the given axis before the given indices.

- __arr__ : array_like : Input array.  
- __obj__ : int, slice or sequence of ints. Object that defines the index or indices before which values is inserted.Support for multiple insertions when obj is a single scalar or a sequence with one element (similar to calling insert multiple times).
- __values__ : array_like. Values to insert into arr. If the type of values is different from that of arr, values is converted to the type of arr. values should be shaped so that arr[...,obj,...] = values is legal.

In [2]:
a = np.array([[1, 1], [2, 2], [3, 3]])
a    

array([[1, 1],
       [2, 2],
       [3, 3]])

In [3]:
np.insert(a,1,5)

array([1, 5, 1, 2, 2, 3, 3])

In [4]:
a

array([[1, 1],
       [2, 2],
       [3, 3]])

In [5]:
a = np.insert(a,1,5)   # So if assignment is done in-place change won't happen 
a       # Also changed from a list of lists to a list

array([1, 5, 1, 2, 2, 3, 3])

In [6]:
b = np.zeros(5)
b

array([ 0.,  0.,  0.,  0.,  0.])

In [7]:
b = np.insert(b,0,22)
b

array([ 22.,   0.,   0.,   0.,   0.,   0.])

In [9]:
b = np.insert(b,1,77)
b

array([ 22.,  77.,   0.,   0.,   0.,   0.,   0.])

In [30]:
type(b)

numpy.ndarray

## np.append(arr, values, axis=None)

Append values to the end of an array.

- arr : array_like : Values are appended to a copy of this array.
- values : These values are appended to a copy of arr. It must be of the correct shape (the same shape as arr, excluding axis). If axis is not specified, values can be any shape and will be flattened before use.
- axis : int, optional
The axis along which values are appended. If axis is not given, both arr and values are flattened before use

In [10]:
np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])  # To combine a python list to a numpy array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
b = np.empty(5)

In [12]:
b = np.append(b,3)
b

array([  4.05492990e-312,   2.98233776e-308,  -3.38460684e+125,
         3.69028917e+180,   6.24389622e-308,   3.00000000e+000])

In [13]:
3.00000000e+000 == 3

True

In [14]:
b = np.append(b,9)
b

array([  4.05492990e-312,   2.98233776e-308,  -3.38460684e+125,
         3.69028917e+180,   6.24389622e-308,   3.00000000e+000,
         9.00000000e+000])

## Learn for multi dimensional refer egs

## Sorting( [Refer](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.sort.html#numpy.sort)  )

Return a sorted copy of an array.

#### numpy.sort(a, axis=-1, kind='quicksort', order=None)[source]

- a : array_like : Array to be sorted.
- axis : int or None, optional : Axis along which to sort. If None, the array is flattened before sorting. The default is -1, which sorts along the last axis.
- kind : {‘quicksort’, ‘mergesort’, ‘heapsort’}, optional: Sorting algorithm. Default is ‘quicksort’.
- order : str or list of str, optionalWhen a is an array with fields defined, this argument specifies which fields to compare first, second, etc. A single field can be specified as a string, and not all fields need be specified, but unspecified fields will still be used, in the order in which they come up in the dtype, to break ties.

__returns: __ sorted_array : ndarray :Array of the same type and shape as a.

In [15]:
from numpy.random import *

In [21]:
a = randint(1,95, (1,14) )
a                           # Obtained a list of list

array([[23, 25, 25, 34, 37, 23, 75, 51, 68, 75, 35, 47, 90, 41]])

In [29]:
type(a)

numpy.ndarray

In [22]:
ab_cpy = np.sort(a)     
ab_cpy

array([[23, 23, 25, 25, 34, 35, 37, 41, 47, 51, 68, 75, 75, 90]])

In [24]:
ab_cpy

array([[23, 23, 25, 25, 34, 35, 37, 41, 47, 51, 68, 75, 75, 90]])

In [25]:
ab_cpy[1:6]

array([], shape=(0, 14), dtype=int32)

In [26]:
len(ab_cpy)

1

In [27]:
ab_cpy

array([[23, 23, 25, 25, 34, 35, 37, 41, 47, 51, 68, 75, 75, 90]])

In [32]:
xy = np.array([74, 49, 55, 15, 91, 82, 49, 51, 83, 36, 66, 89, 17, 72])
xy

array([74, 49, 55, 15, 91, 82, 49, 51, 83, 36, 66, 89, 17, 72])

In [33]:
new_x = np.sort(xy)
new_x

array([15, 17, 36, 49, 49, 51, 55, 66, 72, 74, 82, 83, 89, 91])

In [34]:
new_x[-7:]

array([66, 72, 74, 82, 83, 89, 91])

## Indexing, Slicing and Iterating