In [1]:
import numpy as np

## List for arrays?
Lists in Python are quite general, and can have arbitrary objects as elements. Addition and scalar multiplication are defined for lists. However, lists won't give us what we want for numerical computations as shown in the following examples:

##### Multiplication - repeats:

In [2]:
a = [1,2]
a*2

[1, 2, 1, 2]

In [3]:
2*a

[1, 2, 1, 2]

#### Addition - concatenates:

In [4]:
a = [1,2]
b = [3,4]
a + b

[1, 2, 3, 4]

### If we do the same operations with NumPy, we get:

In [5]:
a = np.array([1,2])
2*a

array([2, 4])

In [6]:
b = np.array([3,4])
a + b

array([4, 6])

### Also, note here that the '*' does component-wise multiplication:

In [7]:
x = np.array(range(5))
x

array([0, 1, 2, 3, 4])

In [8]:
x * x

array([ 0,  1,  4,  9, 16])

One more thing related to the data type before we dive into NumPy section. Unlike lists, __all elements of an np.array have the same type:__

In [10]:
a = np.array([1., 2., 3.])   # all floats
print(a)
a.dtype

[1. 2. 3.]


dtype('float64')

In [11]:
a = np.array([1., 2, 3])     # one float
print(a)
a.dtype                     # all elements become float

[1. 2. 3.]


dtype('float64')

##### NumPy can explicitly state data type:

In [13]:
a = np.array([1, 2, 3], dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


## What's NumPy?
NumPy is a Python extension to add support for large, multi-dimensional arrays and matrices, along with a large library of high-level mathematical functions.

Array Creation

In [14]:
use_me = [ [1,2,3],[4,5,6]]
myArray = np.array(use_me)
myArray

array([[1, 2, 3],
       [4, 5, 6]])

#### Array - zeros(...) & ones(...)
We can fill all elements with zeros.

In [15]:
zero_array = np.zeros((2,4))
zero_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Or ones:

In [16]:
onesArray = np.ones((4,2))
onesArray

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

#### Array - empty(...)
The __np.empty(...)__ is filled with random/junk values:

In [17]:
# It looks like random, but it's not. So, if we need real random numbers, we should not use this empty(...).
emptyArray = np.empty((2,3))
emptyArray

array([[0., 0., 0.],
       [0., 0., 0.]])

### np.arange syntax - step
> numpy.arange([start], stop[, step], dtype=None)

If we want to specify the step, then the start should be spcefied:

In [18]:
a = np.arange(5, 10, 0.5)
a

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

### Array - random(...)

__np.random.random(...)__ is actually using a random number generator to fill in each of the spots in the array with a randomly sampled number from 0 to 1.


In [19]:
randomArray = np.random.random((4,4))
randomArray

array([[0.68955094, 0.1554717 , 0.08288418, 0.10041173],
       [0.06886436, 0.40852304, 0.36190934, 0.73986014],
       [0.62940829, 0.9235217 , 0.95268444, 0.75213133],
       [0.64893891, 0.35568322, 0.036915  , 0.87544867]])

__np.random.randint()__ - generates a random integer.  

We can specify low and high as shown in the example below (low = 1, high = 10)

In [20]:
a = np.random.randint(1, 10, (5,2))
a

array([[5, 2],
       [5, 6],
       [8, 7],
       [1, 4],
       [1, 2]])

### Array - reshape(...)

In [21]:
rArray = np.arange(0,20).reshape((5,4))
rArray

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

- the __arange(...)__ function returns a 1D array similar to what we'd get from using the built-in python function range(...) with the same arguments.  

The __reshape__ method takes the data in an existing array, and puts it into an array with the given shape and returns it.

In [22]:
rArray.reshape((2,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

Note that the original rArray stays there not changed by another reshape(...):

In [23]:
rArray

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

When we use __reshape(...)__, the total number of elements in the array must remain the same. So, reshaping an array with 4 rows and 5 columns into one with 10 rows and 2 columns is fine, but 5x5 or 7x3 would fail:

#### shape
The __shape__ attribute for numpy arrays returns the dimensions of the array. 

If Arr has m rows and n columns, then Arr.shape is __(m,n)__. So Arr.shape[0] is m and Arr.shape[1] is n. 

Also, Arr.shape[-1] is n, Arr.shape[-2] is m.

In [24]:
a = np.arange(10)
print(a)
a.shape

[0 1 2 3 4 5 6 7 8 9]


(10,)

In [27]:
b = a.reshape(5,2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [28]:
b.shape

(5, 2)

In [29]:
b.shape[0]

5

In [30]:
b.shape[1]

2

In [31]:
b.shape[-1]

2

### Array element access

Accessing an array is pretty much straight forward. We access a specific location in the table by referring to its row and column inside square braces.

To get an element, we specify __rArray[row, column]__.

Note that the index starts from 0.


In [32]:
rArray = np.arange(0,20).reshape((5,4))
rArray

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [33]:
rArray[2,3]

11

We can also refer to ranges inside an array:

In [34]:
rArray[3,1:3]

array([13, 14])

In [35]:
rArray[2:5,1:4]

array([[ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

These ranges work just like __slices__ for lists. __s:e:step__ specifies a range that starts at __s__, and stops before __e__, in steps size of __step__. If any of these are left off, they're assumed to be the __s__, the __e+1__ and __1__, respectively.

If we want only the elements in the first column, we do this:

In [36]:
rArray[:,0:5:4]

array([[ 0],
       [ 4],
       [ 8],
       [12],
       [16]])

In [37]:
rArray[:,0]

array([ 0,  4,  8, 12, 16])

If we want only the 0th, 2nd, 4th rows:

In [38]:
rArray[0:5:2,:]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

Or we can left off for the defaults:

In [39]:
rArray

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [42]:
rArray[::3,]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])